export const LOGIN = "LOGIN";
export const LOGIN_SUCCEED = "LOGIN_SUCCEED";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const GET_WORKSPACES = "GET_WORKSPACES";
export const GET_WORKSPACES_SUCCEED = "GET_WORKSPACES_SUCCEED";
export const GET_WORKSPACES_FAILED = "GET_WORKSPACES_FAILED";

export const ADD_WORKSPACE = "ADD_WORKSPACE";
export const ADD_WORKSPACE_SUCCEED = "ADD_WORKSPACE_SUCCEED";
export const ADD_WORKSPACE_FAILED = "ADD_WORKSPACE_FAILED";

export const UPDATE_WORKSPACE = "UPDATE_WORKSPACE";
export const UPDATE_WORKSPACE_SUCCEED = "UPDATE_WORKSPACE_SUCCEED";
export const UPDATE_WORKSPACE_FAILED = "UPDATE_WORKSPACE_FAILED";

export const DELETE_WORKSPACE = "DELETE_WORKSPACE";
export const DELETE_WORKSPACE_SUCCEED = "DELETE_WORKSPACE_SUCCEED";
export const DELETE_WORKSPACE_FAILED = "DELETE_WORKSPACE_FAILED";

export const GET_PROJECTS = "GET_PROJECTS";
export const GET_PROJECTS_SUCCEED = "GET_PROJECTS_SUCCEED";
export const GET_PROJECTS_FAILED = "GET_PROJECTS_FAILED";

export const ADD_PROJECT = "ADD_PROJECT";
export const ADD_PROJECT_SUCCEED = "ADD_PROJECT_SUCCEED";
export const ADD_PROJECT_FAILED = "ADD_PROJECT_FAILED";

export const EDIT_PROJECT = "EDIT_PROJECT";
export const EDIT_PROJECT_SUCCEED = "EDIT_PROJECT_SUCCEED";
export const EDIT_PROJECT_FAILED = "EDIT_PROJECT_FAILED";

// RESOURCES
export const GET_RESOURCES = "GET_RESOURCES";
export const GET_RESOURCES_SUCCEED = "GET_RESOURCES_SUCCEED";
export const GET_RESOURCES_FAILED = "GET_RESOURCES_FAILED";

export const ADD_RESOURCE = "ADD_RESOURCE";
export const ADD_RESOURCE_SUCCEED = "ADD_RESOURCE_SUCCEED";
export const ADD_RESOURCE_FAILED = "ADD_RESOURCE_FAILED";

export const EDIT_RESOURCE = "EDIT_RESOURCE";
export const EDIT_RESOURCE_SUCCEED = "EDIT_RESOURCE_SUCCEED";
export const EDIT_RESOURCE_FAILED = "EDIT_RESOURCE_FAILED";

export const DELETE_RESOURCE = "DELETE_RESOURCE";
export const DELETE_RESOURCE_SUCCEED = "DELETE_RESOURCE_SUCCEED";
export const DELETE_RESOURCE_FAILED = "DELETE_RESOURCE_FAILED";

// TEAMS
export const GET_TEAMS = "GET_TEAMS";
export const GET_TEAMS_SUCCEED = "GET_TEAMS_SUCCEED";
export const GET_TEAMS_FAILED = "GET_TEAMS_FAILED";

// POSITIONS
export const GET_POSITIONS = "GET_POSITIONS";
export const GET_POSITIONS_SUCCEED = "GET_POSITIONS_SUCCEED";
export const GET_POSITIONS_FAILED = "GET_POSITIONS_FAILED";

export const GET_EMAILS = "GET_EMAILS";
export const GET_EMAILS_SUCCEED = "GET_EMAILS_SUCCEED";
export const GET_EMAILS_FAILED = "GET_EMAILS_FAILED";

export const INVITE_TO_WORKSPACE = "INVITE_TO_WORKSPACE";
export const INVITE_TO_WORKSPACE_SUCCEED = "INVITE_TO_WORKSPACE_SUCCEED";
export const INVITE_TO_WORKSPACE_FAILED = "INVITE_TO_WORKSPACE_FAILED";

export const GET_USERS = "GET_USERS";
export const GET_USERS_SUCCEED = "GET_USERS_SUCCEED";
export const GET_USERS_FAILED = "GET_USERS_FAILED";

export const ARCHIVE_USER = "ARCHIVE_USER";
export const ARCHIVE_USER_SUCCEED = "ARCHIVE_USER_SUCCEED";
export const ARCHIVE_USER_FAILED = "ARCHIVE_USER_FAILED";

export const DELETE_USER = "DELETE_USER";
export const DELETE_USER_SUCCEED = "DELETE_USER_SUCCEED";
export const DELETE_USER_FAILED = "DELETE_USER_FAILED";
