export const LOGIN_SUCCEED = "LOGIN_SUCCEED";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const GET_WORKSPACES_SUCCEED = "GET_WORKSPACES_SUCCEED";
export const GET_WORKSPACES_FAILED = "GET_WORKSPACES_FAILED";
