export const LOGIN_SUCCEED = "LOGIN_SUCCEED";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const GET_WORKSPACES_SUCCEED = "GET_WORKSPACES_SUCCEED";
export const GET_WORKSPACES_FAILED = "GET_WORKSPACES_FAILED";

export const ADD_WORKSPACES_SUCCEED = "ADD_WORKSPACES_SUCCEED";
export const ADD_WORKSPACES_FAILED = "ADD_WORKSPACES_FAILED";

export const DELETE_WORKSPACE = "DELETE_WORKSPACE";
export const DELETE_WORKSPACE_SUCCEED = "DELETE_WORKSPACE_SUCCEED";
export const DELETE_WORKSPACE_FAILED = "DELETE_WORKSPACE_FAILED";
